name: publish

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  publish_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: |
          pip install poetry
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry config pypi-token.pypi ${{ secrets.POETRY_PYPI_TOKEN }}
          poetry build
          poetry publish
