name: retag

on:
  workflow_call:
    inputs:
      username:
        description: "The username to use for the container registry"
        required: true
        type: string
      source:
        description: "The image to retag, example: example.azurecr.io/ubuntu:latest"
        required: true
        type: string
      tags:
        description: "The new tags to apply to the image, example: 'prod-v1.0.0,staging-v1.0.0'"
        required: true
        type: string
      environment:
        description: "The GitHub Environment to use"
        required: true
        type: string
    secrets:
      password:
        description: "The password to use for the container registry"
        required: true

jobs:
  retag:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - run: pip install container-tagbot
      - run: tagbot --username="${{ inputs.username }}" --password="${{ secrets.password }}" --source="${{ inputs.source }}" --tags="${{ inputs.tags }}"
